### ISSUE TITLE
DRO support

### ISSUE THREAD

**Issue by IS4Code** [stascorp/MIDIPLEX#1]
Can you please add support for DRO music output, in addition to CMF? It's relatively supported and versatile format for OPL music, and should be quite easy to implement.

**Comment by binarymaster** [comment]
DRO files doesn't contain any MIDI related content. It stores raw OPL2/3 commands instead, and they are not compatible with MIDI at all. So I think this cannot be implemented.

You may be interested in [DRO Trimmer](http://jestarjokin.net/apps/drotrimmer) which supports raw OPL formats and have similar graphical interface.

**Comment by IS4Code** [comment]
Your program is the only one that can open MDI (AdLib) files, and convert them to other formats. DRO conversion would be especially useful in this case, as there's no other program I know that can do the same. To convert MDI to DRO, I had to play them in DOSBox with "MIDI Play" and capture DRO from DOSBox.

**Comment by binarymaster** [comment]
Since DRO files are just raw captures, implementation of MDI to DRO converter is actually an AdLib replayer implementation — this is a huge amount of work, and not related to MIDI at all.

MIDIPLEX supports MDI format because of its specifications. It doesn't have any actual AdLib capabilities for now.

**Comment by binarymaster** [comment]
As a workaround, you may convert MDI files to ROL with MIDIPLEX. Then you can use [AdPlug Winamp plugin](https://github.com/adplug/winamp) to write raw OPL (in RDOS format) files from ROL.

**Comment by IS4Code** [comment]
Is this output in the latest release? I don't find the ROL format in the "Save as" window.

**Comment by binarymaster** [comment]
It's in master branch already, but not in release yet.
