### ISSUE TITLE
Saving multi-track XMI file to MIDI mixes tracks

### ISSUE THREAD

**Issue by ghost** [stascorp/MIDIPLEX#3]
Saving an XMI file with multiple tracks to .MID seems to result in all tracks being mixed together. Any suggestions on how to save each track to a separate .mid file?

**Comment by binarymaster** [comment]
When converting XMI files to MIDI, they are saved in MIDI Type-2 format, which is multi-song - all songs should be played sequently. However some players treat type-2 files as type-1, and playback is incorrect.

Try opening your saved MIDI file, then deleting unneccesary tracks (use `Delete track` button), then save the file.

**Comment by ghost** [comment]
That worked perfectly! Thanks a lot for this handy utility.
